### ISSUE TITLE
Authentication unsuccessful with smtp-mail.outlook.com

### ISSUE THREAD

**Issue by KaiJan57** [marlam/msmtp-mirror#68] opened 2022-03-18 15:27 UTC
I tried setting up msmtp with an Outlook address, but it seems to fail authentication, even though other clients such as Thunderbird can send E-Mail over smtp. I double checked the password and all the other settings but can't find the cause of this authentication failure. Maybe it's a bug in msmtp?
[log.txt](https://github.com/marlam/msmtp-mirror/files/8305742/log.txt)

**Comment by marlam** [comment] 2022-03-20 11:23
This might be related to #67 and maybe #57.
I don't use Outlook or Office365 services myself and therefore cannot debug this alone.
Any additional information that might be helpful would be appreciated (e.g., how does a successful authentication session look like and what is the difference to what msmtp does?)

**Comment by mgladczak** [comment] 2022-05-14 10:25
O365 require OAuth2 token and you can acquire it fairly easy with python. With regards to this topic I'm struggling with issue that msmtp refuses to authenticate with token as the token is longer than 500 chars:
msmtpd    | msmtp: /etc/msmtprc: line longer than 500 characters

**Comment by marlam** [comment] 2022-05-15 10:35
You can work around that limitation by giving the token via `passwordeval`. For your system-wide installation, put the token in some file e.g. `/etc/oauth2-token.txt` and then use in `/etc/msmtprc` the line `passwordeval /usr/bin/cat /etc/oauth2-token.txt`.

Does this work? I'm asking to find out if msmtp passes the OAuth2 token to the server in the way that the server expects it or if there is still some problem there.

The line-length limit for configuration files should be lifted, but that is a different issue.

**Comment by marlam** [comment] 2022-06-25 11:00
Since there was no reply, I assume that the problem is fixed now.

**Closed by marlam** 2022-06-25 11:00 UTC

**Comment by KaiJan57** [comment] 2022-07-06 16:42
Ok, so now I tried sending an email again and it failed authentication in the same manner as before… @mgladczak how exactly do you retrieve an OAuth token? I'm using a standard consumer account, so not the azure stuff many others are using. Are you sure your approach applies to this use case as well? Also, I believe that other clients I use (e.g. K-9 Mail on Android) don't login using any token but just with the plain password, making me suspect that microsoft distrusts msmtp for some reason?
