### ISSUE TITLE
CRAM-MD5 authentication is broken for passwords longer than 64 characters

### ISSUE THREAD

**Issue by vizovitin** [marlam/msmtp-mirror#121] opened 2023-05-19 11:51 UTC
As the title suggests.

### STR
1. Set up an external SMTP server that support CRAM-MD5 authentication
3. Set up local msmtp, set `auth cram-md5` if this is a recent version
4. Set up authentication with an account that has password longer than 64 characters
5. Try to send mail via msmtp
6. (Optionally) Compare the exchange of `msmtp -d ...` with `gen-auth CRAM-MD5 $user $passwd` (from the `sasl2-bin` package on Debian-based system)

### Actual result
Authentication failure.

### Expected result
Authentication is successful, mail is sent.

### Additional information
Problem appears when the password length is 65 characters or more.

[RFC 2195](https://datatracker.ietf.org/doc/html/rfc2195) specifies:

> The shared secret is null-padded to a length of 64 bytes. If the shared secret is longer than 64 bytes, the MD5 digest of the shared secret is used as a 16 byte input to the keyed MD5 calculation.

Relevant [msmtp code](https://github.com/marlam/msmtp-mirror/blob/164d1d0a27c888c4424e79862ae72da06b946606/src/md5-apps.c#L47) (at mirror).

It appears that developers assumed that 2 calls to `MD5_Final` would produce the same digest, but this is not true.

### Patch
Here's a patch to fix this. Since this is a mirror, I'm providing it instead of a PR.

```diff
--- src/md5-apps.c.orig 2023-05-19 09:08:04.623137087 +0000
+++ src/md5-apps.c      2023-05-19 09:10:46.062433734 +0000
@@ -42,21 +42,20 @@

     memset(digest, 0, (size_t)16);
     memset(ipad, 0, sizeof(ipad));
-    memset(opad, 0, sizeof(opad));

     if (secret_len > 64)
     {
         MD5_Init(&context);
         MD5_Update(&context, (unsigned char *)secret, secret_len);
         MD5_Final(ipad, &context);
-        MD5_Final(opad, &context);
     }
     else
     {
         memcpy(ipad, secret, secret_len);
-        memcpy(opad, secret, secret_len);
     }

+    memcpy(opad, ipad, sizeof(ipad));
+
     for (i = 0; i < 64; i++)
     {
         ipad[i] ^= 0x36;
```

**Comment by marlam** [comment] 2023-06-20 07:34
Thank you very much for this detailed report. The issue is fixed now.

I am a bit surprised that this longstanding bug was found now, after CRAM-MD5 is marked as deprecated for many years. I planned to remove it in the next major release (though I don't know yet when this will happen). Do you still have a use case for it?

**Closed by marlam** 2023-06-20 07:34 UTC
