### ISSUE TITLE
address failure when upgrading from 1.6 to 1.8

### ISSUE THREAD

**Issue by geometryof** [marlam/msmtp-mirror#104] opened 2022-10-16 18:35 UTC
I was forced to upgrade msmtp when MS eliminated legacy authentication.  Working great -- thank you!  But in the process one of my other accounts has mysteriously stopped working.

What's weird is that the identical configuration not only works fine when using 1.6, but also when using 1.8 with another account on the same server.  I do not see any obvious configuration errors, nor significant differences when running msmtp -v -- but I'm probably missing something.

Although I do not believe it to be relevant, I note for completeness that my employer's EOL system occasionally fails to receive  messages from this server (comcast), an issue I have never been able to track down -- the messages are being rejected before I can filter them, but I don't know at which end, and there is no consistent pattern or error message.

I'm running Ubuntu 18.04, and using a customized MH-E interface to call msmtp.  The results of msmtp -v are attached separately for 1.6 and 1.8.  The relevant section of my msmtprc file is below.  Thanks in advance for any suggestions.

  account ****
  host smtp.comcast.net
  port 587
  from ****@comcast.net
  tls on
  tls_trust_file ""
  tls_certcheck off
  auth on
  user ****
  password ****
  
[msmtp16.log](https://github.com/marlam/msmtp-mirror/files/9805242/msmtp16.log)
[msmtp18.log](https://github.com/marlam/msmtp-mirror/files/9805244/msmtp18.log)

**Comment by marlam** [comment] 2022-10-16 19:28
Hi, the log files you attached both show success - the mail was accepted by the server. So I'm not sure what the problem is.
Please note that the AUTH lines in the logs only obscure your credentials but can be decoded; you need to change your authentication data.

**Comment by geometryof** [comment] 2022-10-16 22:22
Yeah, me neither.  And ouch; thanks for pointing out my oversight.

**Comment by marlam** [comment] 2023-01-23 19:51
OK, I'll close this now.

**Closed by marlam** 2023-01-23 19:51 UTC
