### ISSUE TITLE
msmtp: cannot get TLS certificate info: error getting SHA256 fingerprint

### ISSUE THREAD

**Issue by samuelharmer** [marlam/msmtp-mirror#43] opened 2021-02-14 18:30 UTC
I'm receiving the following error when trying to configure msmtp, and hoping someone might be able to shed some light on the problem.

    msmtp: cannot get TLS certificate info: error getting SHA256 fingerprint

Full output from `-d` attached as [msmtp -d.txt](https://github.com/marlam/msmtp-mirror/files/5978204/msmtp.-d.txt). Version info attached as [msmtp --version.txt](https://github.com/marlam/msmtp-mirror/files/5978203/msmtp.--version.txt).

I am attempting to use msmtp to relay mail via Google's SMTP relay servers. I'm reasonably certain the SMTP relay is working, as other (non-mstmp) mail is getting through. Interestingly, gnutls-cli seems to be able to STARTTLS successfully (see [gnutls-cli.txt](https://github.com/marlam/msmtp-mirror/files/5978206/gnutls-cli.txt)) so I've also attached [gnutls-cli-debug.txt](https://github.com/marlam/msmtp-mirror/files/5978205/gnutls-cli-debug.txt).

I assume it's coming from [mtls-gnutls.c#L110](https://github.com/marlam/msmtp-mirror/blob/0b1254bc3cfb556bedd5d3240344dbfa3beb3dbe/src/mtls-gnutls.c#L110):

```c
    /* certificate information */
    size = 32;
    if (gnutls_x509_crt_get_fingerprint(cert, GNUTLS_DIG_SHA256,
                tci->sha256_fingerprint, &size) != 0)
    {
        *errstr = xasprintf(_("%s: error getting SHA256 fingerprint"), errmsg);
        gnutls_x509_crt_deinit(cert);
        return TLS_ECERT;
    }
```

I have found an identical [report from macports](https://trac.macports.org/ticket/61994) which suggests its something happening on BSD. According to [`gnutls_x509_crt_get_fingerprint()`](https://gnutls.org/reference/gnutls-x509.html#gnutls-x509-crt-get-fingerprint) that may mean the buffer isn't big enough? I haven't gone digging through that source code yet to see if that's the only error code that might be returned. I can't see what error code is being returned exactly as msmtp is returning `69` which doesn't look like a valid gnutls code.

**Comment by marlam** [comment] 2021-02-15 16:03
Can you try if [this patch](https://github.com/marlam/msmtp-mirror/files/5982699/gnutls-fingerprint-fix-v2.txt) fixes the problem?

**Comment by samuelharmer** [comment] 2021-02-18 08:12
Thanks for the patch.

I think I applied it correctly, but it didn't appear to make any difference.

I'll double-check my method _[I don't often compile packages for BSD]_ and do some more investigation. It looks like `buf_size` could be used to provide a correctly sized buffer if that is indeed the problem.

**Comment by marlam** [comment] 2021-02-18 08:27
Which BSD system do you use? Maybe I can do some tests myself if I get it into a virtual machine.

**Comment by samuelharmer** [comment] 2021-02-18 20:43
It's TrueNAS, the jail is based on FreeBSD 12.2, however I was compiling and installing correctly.

I modded your patch slightly to

```
+    int e = 0;
+    size_t size = 0;
+    size_t real_size = 0;
+    unsigned char* p = NULL;
+
+    e = gnutls_x509_crt_get_fingerprint(cert, algo, NULL, &size);
+    printf("gnutls_x509_crt_get_fingerprint returned %d and size is %d\n", e, size);
```

And it's returning -72 in that first call, so although the docs don't say it returns that, I would assume it's trying to tell me  [GNUTLS_E_ASN1_VALUE_NOT_VALID](https://gnutls.org/reference/gnutls-gnutls.html#GNUTLS-E-ASN1-VALUE-NOT-VALID:CAPS).

**Comment by samuelharmer** [comment] 2021-02-18 21:30
And here's the certificate dump which is making it barf.

```
using account specified on command line
host = smtp-relay.gmail.com
port = 587
source ip = (not set)
proxy host = (not set)
proxy port = 0
socket = (not set)
timeout = off
protocol = smtp
domain = example.com
auth = none
user = (not set)
password = (not set)
passwordeval = (not set)
ntlmdomain = (not set)
tls = on
tls_starttls = on
tls_trust_file = system
tls_crl_file = (not set)
tls_fingerprint = (not set)
tls_key_file = (not set)
tls_cert_file = (not set)
tls_certcheck = off
tls_min_dh_prime_bits = (not set)
tls_priorities = (not set)
tls_host_override = (not set)
<-- 220 smtp-relay.gmail.com ESMTP m18sm141683edc.43 - gsmtp
--> EHLO example.com
<-- 250-smtp-relay.gmail.com at your service, [62.31.31.89]
<-- 250-SIZE 157286400
<-- 250-8BITMIME
<-- 250-STARTTLS
<-- 250-ENHANCEDSTATUSCODES
<-- 250-PIPELINING
<-- 250-CHUNKING
<-- 250 SMTPUTF8
--> STARTTLS
<-- 220 2.0.0 Ready to start TLS
gnutls_x509_crt_get_fingerprint returned -72 and size is 0
	X.509 Certificate Information:
	Version: 3
	Serial Number (hex): 0f40f2bf1a5ccc580300000000cb4080
	Issuer: CN=GTS CA 1O1,O=Google Trust Services,C=US
	Validity:
		Not Before: Tue Jan 26 09:05:20 UTC 2021
		Not After: Tue Apr 20 09:05:19 UTC 2021
	Subject: CN=smtp-relay.gmail.com,O=Google LLC,L=Mountain View,ST=California,C=US
	Subject Public Key Algorithm: EC/ECDSA
	Algorithm Security Level: High (256 bits)
		Curve:	SECP256R1
		X:
			20:b0:68:e8:19:95:b3:01:03:d5:42:a2:a8:38:86:e5
			65:3d:9f:2b:e5:1c:c3:fe:3b:93:69:9d:af:27:50:8b
		Y:
			25:f3:66:ce:f1:26:99:ec:83:45:b6:ee:4e:3e:42:77
			3a:81:e5:23:47:ea:8e:e4:1a:12:fd:b4:ac:b2:60:4d
	Extensions:
		Key Usage (critical):
			Digital signature.
		Key Purpose (not critical):
			TLS WWW Server.
		Basic Constraints (critical):
			Certificate Authority (CA): FALSE
		Subject Key Identifier (not critical):
			360be30736691791a438eef83b0812d489d53510
		Authority Key Identifier (not critical):
			98d1f86e10ebcf9bec609f18901ba0eb7d09fd2b
		Authority Information Access (not critical):
			Access Method: 1.3.6.1.5.5.7.48.1 (id-ad-ocsp)
			Access Location URI: http://ocsp.pki.goog/gts1o1core
			Access Method: 1.3.6.1.5.5.7.48.2 (id-ad-caIssuers)
			Access Location URI: http://pki.goog/gsr2/GTS1O1.crt
		Subject Alternative Name (not critical):
			DNSname: smtp-relay.gmail.com
		Certificate Policies (not critical):
			2.23.140.1.2.2 (CA/B Organization Validated)
			1.3.6.1.4.1.11129.2.5.3
		CRL Distribution points (not critical):
			URI: http://crl.pki.goog/GTS1O1core.crl
		Unknown extension 1.3.6.1.4.1.11129.2.4.2 (not critical):
			ASCII: ......v.D.e......@....(.......1.?.3........w>'.O.....G0E.!..E..O.s.3.....i.7.UR..........7.. i.Wv@.3/.....2k.K.}n.x..Y...D-Zb.v..\./.w0".T..0.V..M..3.../ ..N.d....w>'.......G0E. T....-.Y..H....b+8..=..t..x......!....,... .......|s.gF...:........
			Hexdump: 0481f200f00076004494652eb0eeceafc44007d8a8fe28c0dae682bed8cb31b53fd33396b5b681a8000001773e27a14f0000040300473045022100ef4503b24fbb73e23309c2b983b9698337945552d6c11bb9d4c38711028137fe022069e2577640af332fc984acd81a326bac4bef7d6e8c78c1165900f5d9442d5a62007600f65c942fd1773022145418083094568ee34d131933bfdf0c2f200bcc4ef164e3000001773e27a11e0000040300473045022054d6a28ef22d0a59f3da48adf2a21a622b38d1143d991974d70a78f79c1095ac022100828fac2c08ada820c8f70a998c84fb7c73946746b883d13a00b886e1bb041d83
	Signature Algorithm: RSA-SHA256
	Signature:
		51:bd:cf:2b:d3:08:ee:5a:68:6b:00:76:b3:31:dc:cc
		36:ed:c3:d3:6c:16:42:7a:15:9e:95:e3:f3:e1:a3:67
		4b:ae:f7:d5:bf:6f:ff:eb:10:98:0c:ee:3b:f8:61:1a
		d8:80:c6:00:f3:40:eb:54:15:61:7f:c3:de:7e:1b:a7
		66:93:c4:69:1e:e5:b1:bd:40:54:51:5a:32:cd:a6:29
		08:b8:bd:15:4f:ac:0d:2d:51:b4:79:e0:77:85:e4:2d
		0e:75:12:cc:70:da:b9:6e:51:e7:52:6d:53:75:1f:8e
		b4:38:3e:73:2d:29:1f:1c:3a:3a:0b:e3:cd:3f:79:5a
		c4:07:b4:7a:80:fe:b5:bc:0b:72:0f:d0:38:11:ad:aa
		21:81:3e:96:dc:c0:5d:e1:f1:9a:7d:76:21:b5:dc:7c
		80:66:b5:89:90:e6:c1:c7:8f:3c:13:08:f1:56:99:4a
		77:4e:d0:d8:f1:7f:c3:93:87:b8:e4:85:27:71:c8:9c
		1f:e5:64:16:2d:dd:cc:58:5b:c6:32:24:82:59:92:66
		19:6b:3e:17:d4:8c:d9:6c:20:e7:e7:39:07:bc:1f:dc
		8f:0d:3f:e1:53:9f:5e:7d:c0:da:8e:06:be:37:2a:54
		b6:47:06:90:a3:72:b2:f2:b2:42:4a:95:6e:e1:1d:b4
Other Information:
	Fingerprint:
error: get_fingerprint: ASN1 parser: Value is not valid.
	Public Key ID:
		sha1:1c2919c88f95eee4b06fbc8274ab22306e1039c4
		sha256:f7616f387c0ac33eb8b323cacd4638ef9aa8d2e1705fd1de53f4d88685a431e0
	Public Key PIN:
		pin-sha256:92FvOHwKwz64syPKzUY475qo0uFwX9HeU/TYhoWkMeA=
```

**Comment by marlam** [comment] 2021-02-19 12:26
I still cannot reproduce the problem. From the GnuTLS source code, it looks like `asn1_der_coding()` returns `ASN1_VALUE_NOT_VALID` which GnuTLS then translates to `GNUTLS_E_ASN1_VALUE_NOT_VALID`. I don't think this is supposed to happen. The `asn1_der_coding()` function comes from libtasn1 or the included minitasn1 library (when GnuTLS is configured with `--with-included-libtasn1`). Apparently this problem does not only affect msmtp, see [this thread](https://www.mail-archive.com/freebsd-ports@freebsd.org/msg85196.html). Does a rollback to previous (pre-November) versions of GnuTLS / libtasn1 fix this, or a change between external/internal libtasn1?

**Comment by samuelharmer** [comment] 2021-02-20 09:03
The version of [GnuTLS in FreshPorts](https://www.freshports.org/security/gnutls/) is probably pre-November, as the date in FreshPorts is for 3.6.15 is 2020-09-06.

Building msmtp with OpenSSL works, so the bug is definitely in the must be in msmtp->GnuTLS code path.

### Attempt 1 - roll back libtasn1

- portdowngrade security/libtasn1 r518573 / 4.15.0 / 2019-11-28
- portdowngrade security/gnutls r547781 / 3.6.15 / 2020-09-06
- portdowngrade mail/msmtp r559808 / 1.8.14 / 2021-01-01

msmtp: cannot get TLS certificate info: error getting SHA256 fingerprint

### Attempt 2 - also roll back gnutls

- portdowngrade security/libtasn1 r518573 / 4.15.0 / 2019-11-28
- portdowngrade security/gnutls r524943 / 3.6.12 / 2020-02-02
- portdowngrade mail/msmtp r559808 / 1.8.14 / 2021-01-01

msmtp: cannot get TLS certificate info: error getting SHA256 fingerprint

### Attempt 3 - ?

Looking at [libtasn1#30](https://gitlab.com/gnutls/libtasn1/-/issues/30) and the symptoms this feels like it might be clang related. I'll have a play later with compiler options.

**Comment by samuelharmer** [comment] 2021-02-20 11:59
Definitely seems like the problem is not with msmtp. I'm leaning towards forgetting GnuTLS with clang 10 until clang is patched to stop doing dodgy optimisations or GnuTLS can work around clang's "optimisations".

**Comment by marlam** [comment] 2021-04-20 14:44
I'm closing this now. Even though msmtp does not seem to be the problem here, it uses a safer way to get fingerprints from GnuTLS since commit a4f09c8684103084b71ca8d2f89b86b97dc456b3 which is in version 1.8.15.

**Closed by marlam** 2021-04-20 14:44 UTC
