### ISSUE TITLE
to address is not complete sending local via aliases

### ISSUE THREAD

**Issue by AleksCee** [marlam/msmtp-mirror#98] opened 2022-09-02 07:32 UTC
Hi, I have the same issue like #65 with the version in Ubuntu 22.04 LTS: msmtp Version 1.8.16

I have configured an alias like this:
palms: mail@alex*******.de
If I use mail like this:
echo test | mail -s test palms
The mail did not reach me. The alias seams to be only set in RCPT TO:<mail@alex******.de> but in To: is only the given cmd parameter „palms“.

I have also traced this via debug:

```
--> MAIL FROM:<root@p*******.de>
--> RCPT TO:<mail@alex********.de>
--> DATA
<-- 250 2.1.0 Sender ok
<-- 250 2.1.5 Recipient ok
<-- 354 3.0.0 Enter data for mail with id 61010dy826sTlJJ
--> From: root@p******.de
--> Subject: test
--> To: palms
--> User-Agent: mail (GNU Mailutils 3.14)
--> Date: Fri,  2 Sep 2022 08:54:29 +0200
--> 
--> test
--> .
<-- 250 2.0.0 queued as 61010dy826sTlJJ
--> QUIT
```

My workaround for now is a intermediate sed Script vor /usr/sbin/sendmail with is replace all From/To without an @ before piping the mail to msmtp. But I don‘t like this way, I like to use the standard/default.

```
cat /usr/sbin/sendmail 
#!/bin/bash
sed -e '/From:[^@]*$/ s/From:.*$/From: cloud@p******.de/;/To:[^@]*$/ s/To:.*$/To: cloud@p******.de/;' | /usr/bin/msmtp $@

```
Can you say what the problem is in my case? 

If I use a full address (with an @) it’s work: echo test | mail -s test mail@alex******.de

Thanks, Alex

**Comment by marlam** [comment] 2022-09-02 07:57
This works as intended: aliases only change the recipient addresses for the mail envelope but do not rewrite the To, Cc etc headers.
The headers are only informational and may contain e.g. a mailing list addresses. They are completely independent from the mail envelope (MAIL FROM and RCPT TO in the SMTP session).
This can not be the reason why the mail did not reach you; maybe it was just classified as spam by some system.

**Comment by marlam** [comment] 2022-09-02 08:38
I added a note to the documentation to make that clearer.

**Comment by AleksCee** [comment] 2022-09-02 09:03
It‘s seams that Strato.de and/or GMX.de emails with an incomplete from/to address (without an @) not accepting… have you an Idee for a better solution than my sed script for this case? The script is working but it‘s not the perfekt way I think.

**Comment by marlam** [comment] 2022-09-02 09:07
But in the session you posted above the SMTP server answers `250 2.0.0 queued as 61010dy826sTlJJ` which means it accepted the mail and took responsibility to either deliver it or notify you of delivery failure.

**Comment by AleksCee** [comment] 2022-09-02 09:18
The address is an only forwarding account, and the mails with the to: palms header are not reaching the GMX Account. I have copy the mail befor forwarding at Strato, so I have seen the To header in the mail. But no forwarding error or anything in spam on GMX can found. I will try an other alias to send the mail direkt to GMX to check what‘s happened there. Can test it at afternoon.

**Comment by AleksCee** [comment] 2022-09-02 16:32
Ok, I have try it. When I use alias to map my GMX address directly the answer is:

> <<< 554 Transaction failed Reject due to policy restrictions. For 
>       explanation visit 
>       https://www.gmx.net/mail/senderguidelines?ip=81.169.146.216&c=hi

and on the linked page is one of the rules:

> Ensure that the following email headers included in your message are syntactically correct: Date, From, Sender, **To**.

perhaps the meaning of syntactically in this was is name@domain.tld is think…?

**Comment by marlam** [comment] 2022-09-02 17:19
Yes, that may be the case.
You could use `palms:;` instead of `palms` to make it syntactically correct (as a group name).
Or you could use the big gun and use `undisclosed_recipients on` in your msmtp configuration to replace all To/Cc/Bcc headers with `To: undisclosed-recipients:;`, which is syntactically correct and explicitly mentioned in the RFCs.
Or you could tell the `mail` program to not use the msmtp `-t` option to read recipients from the mail, and instead list them on the command line explicitly. That way you would be free to set the To header in any way you want, while the local alias `palms` would still be replaced by msmtp in the mail envelope.
Would any of these options work for you?

**Comment by AleksCee** [comment] 2022-09-03 09:40
- where have I use the palms:; ? In the alias or in cmd as parameters for mail?
- undisclosed-recipients seams not the best way, as you say „big gun“ ;)
- the last way: I use mail as an pip command and use only the alias „palms“ so the to know the mail header is set to palms. In this case I musst change all the scripts to use a full address as parameter for mail, right?

**Comment by marlam** [comment] 2022-09-03 15:48
The palms:; would belong in the To header, but if you cannot control that independently from the envelope recipient list, then this does not make sense.
Currently, the only way to avoid giving the full address everywhere (thereby disabling alias expansion) is the `undisclosed_recipients on` method.
There is currently no plan to implement a header rewrite mechanism.
Therefore, I'm closing this issue now.

**Closed by marlam** 2022-09-03 15:48 UTC

**Comment by markstos** [comment] 2023-02-24 22:03
There's a discussion about automating the "sendmail wrapper" workaround above at  https://github.com/chriswayg/ansible-msmtp-mailer/issues/14
