### ISSUE TITLE
syntax error near unexpected token `libgnutls,'

### ISSUE THREAD

**Issue by kata32** [marlam/msmtp-mirror#72] opened 2022-04-08 07:56 UTC
I am trying to compile msmtp 1.8.20 on Debian 10, at the command "./configure; make; make install" I get the following error:

```
...
checking for library containing res_query... -lresolv
./configure: line 7732: syntax error near unexpected token `libgnutls,'
./configure: line 7732: `    PKG_CHECK_MODULES(libgnutls, gnutls >= 3.4, HAVE_LIBGNUTLS=1, HAVE_LIBGNUTLS=0)'
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

**Comment by kata32** [comment] 2022-04-15 08:22
I fixed myself:
pkg-config package was missing, it is a debian 10 without gui, this may be the reason?
I find that the command give me a warning 'configure: WARNING: No package 'libsecret-1' found', I installed it the warning gone away.

Now give me a new error:
.
.
.
`checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating po/Makefile.in
config.status: creating doc/Makefile
config.status: creating scripts/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: error: in `/root/msmtp':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
`

I don't understand what should I do

**Comment by marlam** [comment] 2022-04-15 08:33
That error message is not in the `configure` script that is part of version 1.8.20 (it uses a slightly different wording). Did you run `autoreconf` or similar, or edited `Makefile.am` or `configure.ac`
In any case, did you look at `config.log`? Can you post that file?

**Comment by kata32** [comment] 2022-04-15 09:08
I look at config.log, I understand that build-essential package was missing, LOL, you understand that I'm not a linux guru :-)

After that I get this error
```
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.20 but the autoconf macros are from gettext version 0.19
```
But I should have found the solution in https://github.com/marlam/msmtp-mirror/issues/55

Now everything seems to be working

A tip, in the notes you could specify all the necessary packages otherwise other inexperienced users like me will not succeed

**Comment by marlam** [comment] 2022-05-04 16:09
Hm, I cannot draw a clear conclusion from this since I cannot reproduce the problem and `build-essential` is specific to Debian. Since the problem seems to be solved for you, I'll close this now.

**Closed by marlam** 2022-05-04 16:09 UTC
